#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RugbyLeagueMobileApp.Resource", IsApplication=true)]

namespace RugbyLeagueMobileApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int btnAddNewPlayerToTeam = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int btnAddPlayer = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int btnAddPlayerToTeam = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int btnCreateNewTeam = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int btnFinished = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int btnReturnHome = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnSaveNewPlayer = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int btnViewPlayerData = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int btnViewTeam = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int etFirstName = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int etNickname = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int etNumberInput = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int etPlayerPosition = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int etSurname = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int lvNewTeam = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int lvPlayers = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int lvTeamPlayers = 2131099671;
			
			// aapt resource value: 0x7f060009
			public const int spinnerPlayerSelector = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int tvAssignNumber = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int tvAssignPosition = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int tvFirstName = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int tvLastName = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int tvSelectPlayer = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int tvSurname = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddPlayer = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CreateTeam = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ViewPlayers = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ViewTeam = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
